GET http://localhost:3001/blogs

###

POST http://localhost:3001/blog/new
Content-Type: application/json

{
    "title":"test title 5",
    "author":"seneth 5",
    "description":"somthing somth 5"
}

###

DELETE http://localhost:3001/blog/delete/661bda6618b6d33ce7f72b01