GET http://localhost:3001/blogs

###

POST http://localhost:3001/blog/new
Content-Type: application/json

{
    "title":"test title 6",
    "author":"seneth 6",
    "description":"somthing somth 6"
}

###

DELETE http://localhost:3001/blog/delete/661bda2d18b6d33ce7f72afe